### ISSUE TITLE
Visit line plot needs to have more hover information: e.g., the actual (not normalized) value, and the visit number for each point.

### ISSUE THREAD

**Issue by brendancol** [Quansight/lsst_dashboard#106]
Visit line plot needs to have more hover information: e.g., the actual (not
normalized) value, and the visit number for each point.

**Comment by chbrandt** [comment]
Commit https://github.com/Quansight/lsst_dashboard/commit/817af7a0322a4dc98ccebed493cfdbf947400e2a (currently in branch `visits_plot_tabs_hover`) addresses this issue. @brendancol
