### ISSUE TITLE
Group visit line plots in tabs by filter. Different metrics from the same filter should be overlays, but different filters, if present, should spit into tabs.

### ISSUE THREAD

**Issue by brendancol** [Quansight/lsst_dashboard#107]
Group visit line plots in tabs by filter. Different metrics from the same filter should
be overlays, but different filters, if present, should spit into tabs.

**Comment by brendancol** [comment]
Tabs have been added to the detail plot.

@chbrandt @philippjfr there might be a bug on the holoviews side which we'd like to chat about.

When changing filter tabs on the detail screen, the axes of the visit plot don't update correct. 

@chbrandt is going to create a reproduction case

**Comment by chbrandt** [comment]
The bug/feature was bypassed by giving a unique name for the x-axis of each filter in the visits plot: _e.g._ `visits (HSC-G)`. Before, all plots -- in each different tab (separated after the filter label) -- had the same (internal) label for x-axis, `visit`; When put together in a Tab container the values whould be concatenated.

**Comment by chbrandt** [comment]
Commit https://github.com/Quansight/lsst_dashboard/commit/29ace33b7c6b5fa092af74a31257b534f736cfa4 fix this issue. @brendancol
