### ISSUE TITLE
maintain zoom level/position when the number of metrics changes

### ISSUE THREAD

**Issue by brendancol** [Quansight/lsst_dashboard#108]
When adding or removing a metric, the plots currently always reset. They should
instead maintain zoom level/position when the number of metrics changes

@philippjfr you mentioned there was an easy this, can you points us in the right direction?

**Comment by timothydmorton** [comment]
Also, just to add to this issue, this should be solved in conjunction with solving (or on the way toward) general state persistence, not just of zoom/pan level of individual plots.  A related use case to keep in mind here is that someone might want to be able to make some selection of points in the dashboard, and then explore that same selection in some ad-hoc analysis in a notebook.  So not yet the full "explore in jupyter" button, but perhaps something where a text query defining the data selection can be copied from the dashboard to be pasted & used elsewhere.

**Comment by timothydmorton** [comment]
Oh, sorry; I hadn't seen #109

**Comment by dharhas** [comment]
fixed in #146
