### ISSUE TITLE
Add 'Drill Down'  plot based on interactions with the Visit Line plot in the Detail View.

### ISSUE THREAD

**Issue by brendancol** [Quansight/lsst_dashboard#110]
Visit plot visualization: clicking on a point (or selecting multiple points) in the
visit timeseries plot should switch the scatter/sky plots in the detail view to reflect
the data for only that visit (or visits). Then there should be a "back to coadd,"
along with a title of some sort (below the visit plot) to indicate whether coadd or
visit (and which visit(s)) is being viewed. ← goal is drill down QA. show scatter plot and skyplot of the particular visit. If we can zoom in on visit level plots and pick a point and show a thumbnail of image (killer feature if we can get it in). Need to use LSST/Butler infrastructure to get the image.

- Click on visit plot
- Bring up data for visit plot

Question: get locations of the images to link to?

**Comment by dharhas** [comment]
- [ ] @brendancol - Please make a wireframe of what this might look like
- [ ] @timothydmorton - can you review and approve the wireframe
- [ ] @philippjfr - Once they are done can you hook up the pieces to make things functional
- [ ] @brendancol or @dharhas write a fn to get correct metric and skyplot data for a given metric and visit id.

**Comment by timothydmorton** [comment]
Regarding the last bit here regarding "click the point to get a postage-stamp image," this is a feature that if we can put it in, it doesn't need to be restricted to the drill-down visit plot.  In fact, we only have two kinds of plots at this point that show points: the "sky plot" and the "scatter plot."  If both of these could have a built-in "click-> view thumbnail" ability, then all we need is to connect an appropriate "load_thumbnail" function behavior to that action, and that would depend on whether it was the coadd or visit data, and then this functionality would be available either from the "skyplot view" or "detail view" (and the latter in both coadd and visit mode).  The content of `load_thumbnail()` would be up to me to figure out, but if the action could be connected to a dummy function that returns, e.g., a 100x100 pixel demo image, that would be all we would need to make this possible.
