### ISSUE TITLE
Implement a third “summary view” to the dashboard

### ISSUE THREAD

**Issue by brendancol** [Quansight/lsst_dashboard#111]
Summary metric visualization: Implement a third “summary view” to the dashboard (beyond “sky view” and “detail view”); this would show spatial heatmaps of the summary metrics provided by ‘validate_drp’ (one number per
tract) ← important for march 17th..

**Comment by brendancol** [comment]
The might be integrated as a separate dashboard.  This view will sit above the currently dashboard allow for selection of the initial dataset

**Comment by timothydmorton** [comment]
The viz for this separate summary dashboard should follow the basic shape of what's currently in notebooks/tract-viz.ipynb.  @kcpevey we need to add selections to this; I think for now until the new polygon box-selection is implemented, multiple tap selections should be fine to select the desired tracts to drill down

**Comment by timothydmorton** [comment]
@brendancol the dashboard behavior should look something like this:
- grab the full skymap json from somewhere in this repo (locally probably better than via http)
- load a (still-to-be-defined) butler dataset that has the summary metrics in a table, indexed by tract number
- join this to the skymap to get the polygon info
- viz with hv using the polygon workaround @kcpevey did in the notebook (this viz should be one tab per filter; I think probably the butler datasets will be separated by filter)
- this viz will need to support selections (ideally box/lasso selectable, but maybe for now just taps), and then once a selection is finalized, then there could be a "drill-down" button that launches the drilldown dashboard on that selection.

Lemme know if there's anything you'd like to clarify further!

**Comment by timothydmorton** [comment]
For selecting, I could also imagine a text-entry panel element where you could also define a selection of tracts by entering them in (and maybe that could also be linked to the selection on the plot, such that e.g., entering a tract or range of tracts there selects them on the viz as well).  If this is too ambitious, we can table for the first draft of this, but just to put it out there.

**Comment by timothydmorton** [comment]
Suggesting that last thing because sometimes someone might know the *number(s)* of tracts that they want to look at in more detail, but not exactly where they are on the sky.

**Comment by timothydmorton** [comment]
Also, we will want a dropdown selection on which summary metric to be displayed (e.g., the color dim should be dynamic).  Or maybe even better: the same UI concept as currently in the 'skyplot view'---a checkbox element grouped by filter, with the summary-polygon-view tabbed and displaying the checked elements.  I actually like this idea, as I can imagine people wanting to simultaneously view different combinations of summary metric/filter in the same way that's currently possible in skyplot view.  @brendancol @kcpevey what do you think?  

The contents of this checkbox would be different from what we have now (the summary metrics do not correspond to what we are currently calling 'metrics' in the rest of the dashboard)

**Comment by brendancol** [comment]
@timothydmorton @dharhas fixed in https://github.com/Quansight/lsst_dashboard/pull/137
