### ISSUE TITLE
Scatter plot misaligned?

### ISSUE THREAD

**Issue by timothydmorton** [Quansight/lsst_dashboard#135]
The scatter plot on the left should not look like this.  The full (grey) and selected (color) should be the same by default on load. 
<img width="1711" alt="Screenshot 2020-03-13 12 15 52" src="https://user-images.githubusercontent.com/1895387/76652857-a9c96e80-6524-11ea-9c11-0656e8dd7f71.png">
I see this on both the test datasets on lsst-dev

**Comment by timothydmorton** [comment]
another example.  the colored point are definitely flipped (at least)
<img width="1711" alt="Screenshot 2020-03-13 12 34 02" src="https://user-images.githubusercontent.com/1895387/76653919-fd3cbc00-6526-11ea-93ce-c507f6339177.png">

**Comment by philippjfr** [comment]
Fixed in HoloViews 1.13.0b9.
