### ISSUE TITLE
Precompute Visit Datasets.

### ISSUE THREAD

**Issue by dharhas** [Quansight/lsst_dashboard#153]
Currently there are some groupbys and means/medians that are calculated before generating the visit line plots. These should be precomputed and saved to disk. The dashboard code should just load these in.

**Comment by timothydmorton** [comment]
If the visit tables are partitioned by filter, tract, and visit, then these summary tables could be essentially just the result of calling `.describe()` on each filter/tract/visit partition, and that saved to a single table, indexed by filter/tract/visit.  That's my suggestion for how to organize this.
