### ISSUE TITLE
Dashboard: Convert to using Jinja2 Template instead of current panel() layout

### ISSUE THREAD

**Issue by brendancol** [Quansight/lsst_dashboard#19]
Example Template: https://panel.pyviz.org/user_guide/Templates.html

**Comment by brendancol** [comment]
```python
from jinja2 import Environment, FileSystemLoader

env = Environment(loader=FileSystemLoader('.'))
jinja_template = env.get_template('sample_template.html')

tmpl = pn.Template(jinja_template)

tmpl.add_panel('A', hv.Curve([1, 2, 3]))
tmpl.add_panel('B', hv.Curve([1, 2, 3]))
```

**Comment by chbrandt** [comment]
If we put the whole page inside a template we can do it. The idea of having only certain parts of the layout organized by Jinja is cool but not doable (afaiu), `panel.Template` objects do not render from inside other layout objects (`Row`, `Column`) (in fact, they are a completely [different kind of object](https://github.com/pyviz/panel/blob/c74663796bd61a27d895e3de7fcbddf78e20d0aa/panel/template.py#L23)).
