### ISSUE TITLE
Fix Linked Axes Tabs on Skyplot

### ISSUE THREAD

**Issue by brendancol** [Quansight/lsst_dashboard#28]
The Tabs are created here in `lsst_dashboard/gui.py::linked_tab_plots(self)`.

**Comment by dharhas** [comment]
more specifically, only the first tab redraws, the others don't

**Comment by chbrandt** [comment]
@dharhas As of version a4b6758d6bff454490c9839dc17a8870cf03c914 Skyplots are working (I think) as expected. Follows a series of screenshots where two plots have their datapoints moved in the canvas.

* init:
<div style="display:inline">
<img width="250" alt="Screen Shot 2019-09-19 at 21 54 27" src="https://user-images.githubusercontent.com/482051/65277078-74216b00-db29-11e9-8d0d-2196b86cacb6.png">
<img width="250" alt="Screen Shot 2019-09-19 at 21 54 53" src="https://user-images.githubusercontent.com/482051/65277118-8d2a1c00-db29-11e9-8c0d-70122d5725e8.png">
</div>
<hr/>

* move _first tab/plot_
  * _second tab/plot_ updates
<div style="display:inline">
<img width="250" alt="Screen Shot 2019-09-19 at 21 55 39" src="https://user-images.githubusercontent.com/482051/65277435-2eb16d80-db2a-11e9-9b7a-b55596b6bfb5.png">
<img width="250" alt="Screen Shot 2019-09-19 at 21 55 53" src="https://user-images.githubusercontent.com/482051/65277451-353fe500-db2a-11e9-9333-f4e295314b49.png">
</div>
<hr/>

* move _second tab/plot_
  * _first tab/plot_ updates
<div style="display:inline">
<img width="250" alt="Screen Shot 2019-09-19 at 21 56 21" src="https://user-images.githubusercontent.com/482051/65277463-3bce5c80-db2a-11e9-81d0-e1af8d22b06b.png">
<img width="250" alt="Screen Shot 2019-09-19 at 21 56 36" src="https://user-images.githubusercontent.com/482051/65277474-425cd400-db2a-11e9-8b13-a0bd3ee2bb4b.png">
</div>
<hr/>

* reset _first tab/plot_
  * _second tab/plot_ updates
<div style="display:inline">
<img width="250" alt="Screen Shot 2019-09-19 at 21 56 58" src="https://user-images.githubusercontent.com/482051/65277489-47ba1e80-db2a-11e9-9a32-65ccd90f5e21.png">
<img width="250" alt="Screen Shot 2019-09-19 at 21 57 10" src="https://user-images.githubusercontent.com/482051/65277497-50125980-db2a-11e9-9d46-c45e0243f081.png">
</div>

**Comment by timothydmorton** [comment]
@philippjfr just to return to this, as I'm now able to check things out here-- this is still an open issue, in that the datashaded maps on the linked tabs do not resample upon zoom.
<img width="1283" alt="Screenshot 2019-12-03 15 00 47" src="https://user-images.githubusercontent.com/1895387/70097247-c711a700-15dd-11ea-8e59-ab89540f5b1a.png">
<img width="1291" alt="Screenshot 2019-12-03 15 00 41" src="https://user-images.githubusercontent.com/1895387/70097248-c711a700-15dd-11ea-8951-e0b37415149e.png">
Any suggestions?  Clue for me is that the console displays the following repeatedly:
```
Parameter name clashes for keys {'y_range', 'x_range'}
```
Perhaps in the different tabs we just have to rename those dimensions somehow?

**Comment by philippjfr** [comment]
I can't actually reproduce the issue you're describing so I'd have to know more about your environment.

>Parameter name clashes for keys {'y_range', 'x_range'}

This is annoying but does not indicate an actual issue so is likely unrelated.

**Comment by timothydmorton** [comment]
```(lsst-scipipe) [tmorton@lsst-dev01 ~]$ panel --version
panel 0.7.0.post7+g088e33c```
and I've just pip-installed hv, bokeh, datashader etc fresh. 

Haven't tried to make a minimal example yet, so I'll have to dig into what's happening in the code a bit.

**Comment by dharhas** [comment]
I can merge @timothydmorton latest PR in and make a new test dataset, so we can test this locally without being dependent on the LSST cluster stack (which is a kludgy mix of conda & pip). I had scene this too but I'm not currently sure if I only saw it on cluster deployments or local as well.

**Comment by dharhas** [comment]
@philippjfr I've updated master to work on local test datasets. The download.sh contains links to two test datasets one around 750mb and the other around 6gb as tar.gz files. They need to be untarred after download. I'm seeing the same behavior with only the first tab reshading/resampling in a clean local env with latest panel master and the smaller test dataset. Haven't checked the larger but I assume it will be the same.

**Comment by timothydmorton** [comment]
@philippjfr here's a minimal demo:

```python
import holoviews as hv
import numpy as np
import panel as pn
import pandas as pd
from holoviews.operation.datashader import datashade
import datashader as ds

pn.extension()

N = 1000000
x = np.random.random(N)
y = np.random.random(N)

dset = hv.Dataset(pd.DataFrame({'x': x,
                              'y': y, 
                              'z1': x*y,
                              'z2': -x*y}))

pts1 = hv.Points(dset, kdims=['x', 'y'], vdims=['z1'])
pts2 = hv.Points(dset, kdims=['x', 'y'], vdims=['z2'])

opts = dict(height=800, width=800)
plot1 = datashade(pts1, aggregator = ds.mean('z1')).options(**opts)
plot2 = datashade(pts2, aggregator = ds.mean('z2')).options(**opts)

pn.Tabs(*[('z1', pn.panel(plot1)), ('z2', pn.panel(plot2))])
```
For me, only the first tab re-renders the datashaded image.  Is this an issue for hv, datashader, or panel?

**Comment by timothydmorton** [comment]
https://github.com/holoviz/panel/issues/845

**Comment by philippjfr** [comment]
As far as I can tell this is resolved when using latest Panel/HoloViews.
