### ISSUE TITLE
Hookup Count HTML message into new template

### ISSUE THREAD

**Issue by brendancol** [Quansight/lsst_dashboard#31]

**Comment by brendancol** [comment]
- [ ] added component to top of metrics area
- [ ] hookup actual values

**Comment by chbrandt** [comment]
@brendancol I commit in branch [hookup_counters](https://github.com/Quansight/lsst_dashboard/tree/hookup_counters) an approach. Styling has to be worked out, either in the top navbar or as a foot-bar. The counting implemented so far consider:
* all filters current loaded (e.g., RIZ) in the case of `tracts` and `patch`
* all selected metrics in the case of `visits`

**Unique objects** count is not implemented yet. I understand I have to talk to Tim about that.
