### ISSUE TITLE
Review existing Holoview / Param / Bokeh Example

### ISSUE THREAD

**Issue by brendancol** [Quansight/lsst_dashboard#5]
@dharhas can you put a link to tim's repo here:

**Comment by dharhas** [comment]
Examples:

https://github.com/lsst-dm/qa_explorer/blob/master/python/lsst/qa/explorer/plots.py

http://nbviewer.ipython.org/urls/raw.github.com/lsst-dm/qa_explorer/master/notebooks/coadd-demo.ipynb
