### ISSUE TITLE
doctr is not pushing to gh-pages due to a key error.

### ISSUE THREAD

**Issue by dharhas** [Quansight/lsst_dashboard#87]
Looks like we may need to sort out the key stuff again.

See here: https://travis-ci.org/Quansight/lsst_dashboard/jobs/587496380

```
ERROR: The doctr command '/home/travis/miniconda/envs/lsst-panel/bin/doctr deploy . --built-docs ./docs/_build/html/' failed: RuntimeError("DOCTR_DEPLOY_ENCRYPTION_KEY_QUANSIGHT_LSST_DASHBOARD or DOCTR_DEPLOY_ENCRYPTION_KEY environment variable is not set. Make sure you followed the instructions from 'doctr configure' properly. You may need to re-run 'doctr configure' to fix this error.")
Error: DOCTR_DEPLOY_ENCRYPTION_KEY_QUANSIGHT_LSST_DASHBOARD or DOCTR_DEPLOY_ENCRYPTION_KEY environment variable is not set. Make sure you followed the instructions from 'doctr configure' properly. You may need to re-run 'doctr configure' to fix this error.```

**Comment by ppwadhwa** [comment]
I created a new branch to address this issue.  I created a new key and tested it and it is writing files to the gh-pages branch.  I'm not sure if something is happening when you try to pull it to the master?

**Comment by dharhas** [comment]
Do a PR with the new key and I can merge to test.

**Comment by kcpevey** [comment]
@dharhas @ppwadhwa What's the status of this?

**Comment by dharhas** [comment]
@kcpevey I assume we broke documentation when we moved to github actions?

**Comment by kcpevey** [comment]
Yes, closing in favor of https://github.com/Quansight/lsst_dashboard/issues/120
