### ISSUE TITLE
Adding/removing a metric resets skyplot to home zoom level/pan position

### ISSUE THREAD

**Issue by timothydmorton** [Quansight/lsst_dashboard#93]
A common use case might be to zoom in on a region of the sky plot and then add a metric, wishing to see it at that same location.  As it is now, adding or removing a metric fully resets the sky plot.  Perhaps this can be addressed by independently keeping intentional track of the x_range and y_range of the skyplots, such that new plots are loaded with those ranges.

**Comment by timothydmorton** [comment]
This might relate to #28 as well.

**Comment by philippjfr** [comment]
>Perhaps this can be addressed by independently keeping intentional track of the x_range and y_range of the skyplots, such that new plots are loaded with those ranges.

I'd create RangeXY streams once on initialization and then reuse them and initialize the x_range and y_range parameters on the rasterize call with their values.
