### ISSUE TITLE
Linked scatter/sky plots not working

### ISSUE THREAD

**Issue by timothydmorton** [Quansight/lsst_dashboard#99]
The linked plots in detail view do not work.  I have tested with both panel current master and 0.7.1a2, (holoviews 1.12.7) and am seeing the following behavior:
* I first select two metrics (e.g., Gaussian-PSF mag in two different filters)
* I switch to "detail view"
* None of pan, box zoom, or box select tools seem to work on the scatter/sky plots
* When I zoom in (on, e.g., one of the scatter plots), the plots flash spasmodically and become unresponsive, accompanied by a fast, continuous repeating scroll of `Parameter name clashes for keys {'y_range', 'x_range'}` in the terminal where the panel server is running. 
For what it's worth, two instances of `Parameter name clashes for keys {'height', 'width', 'scale'}` show up in the console before that.

@philippjfr I don't know how closely you had been following the development of the linked plots for this project, but @dharhas mentioned to me in December that some of the ideas tested out here were going to be included in future (present?) holoviz releases.  Is it possible that recent updates to the holoviz code may have broken some of the linking code that @brendancol had done here?

**Comment by philippjfr** [comment]
I'm not aware of any changes, those warnings you are seeing are also unrelated. Indeed the versions you are testing are largely unchanged from those that were used at the time this was implemented. I'll likely take a look at it today or tomorrow since I'm hoping to release panel 0.8 tomorrow.

**Comment by dharhas** [comment]
@philippjfr There is a test dataset I used at Pydata Austin that is in the right format to use with the latest LSST code. It is located here: https://quansight.nyc3.digitaloceanspaces.com/datasets/lsst/DM-21335-1Perc.tar.gz

Let me know if you need help debugging.

**Comment by philippjfr** [comment]
Could you try again using Panel v0.8.0a1 before I dive in?

**Comment by timothydmorton** [comment]
OK, with v0.8.0a1 it looks like if I turn off then back on the pan tool (mimicking what Dharhas did in the Austin talk), then things might work as expected?  But before doing that, nothing.  If indeed that is all that is required to make things work (and that works reliably), then this is just a minor bug, but if you can figure out what's happening @philippjfr that would be awesome, thanks!

**Comment by philippjfr** [comment]
>OK, with v0.8.0a1 it looks like if I turn off then back on the pan tool (mimicking what Dharhas did in the Austin talk), then things might work as expected? 

This is a bokeh toolbar bug which can hopefully be resolved soon.
